# Given a profile matrix Profile, we can evaluate the probability of every k-mer in a string Text and find a Profile-most probable k-mer in Text, i.e., a k-mer that was most likely to have been generated by Profile among all k-mers in Text. For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT. Indeed, every other 12-mer in this string has probability 0. In general, if there are multiple Profile-most probable k-mers in Text, then we select the first such k-mer occurring in Text.
# 
# Profile-most Probable k-mer Problem: Find a Profile-most probable k-mer in a string.
# 
# Input: A string Text, an integer k, and a 4 × k matrix Profile.
# Output: A Profile-most probable k-mer in Text.

# Sample Input:
#   
#   ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT
# 5
# 0.2 0.2 0.3 0.2 0.3
# 0.4 0.3 0.1 0.5 0.1
# 0.3 0.3 0.5 0.2 0.4
# 0.1 0.2 0.1 0.1 0.2
# Sample Output:
#   
#   CCGAG

mystring <- "ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT"

mystr <- mystring %>% str_split(., "") %>% .[[1]]

k <- 5
# generate all the k-mer 

# create a place holder list
mylist <- vector(mode = "list", length = (length(mystr) - k + 1))

# put all the K-mer into mylist
for (i in 1:(length(mystr) - k + 1)) {
  mylist[[i]] <- mystr[i:(i + k - 1)]
}


profile <- rbind(
  A <- c(0.2, 0.2, 0.3, 0.2, 0.3),
  C <- c(0.4, 0.3, 0.1, 0.5, 0.1),
  G <- c(0.3, 0.3, 0.5, 0.2, 0.4),
  T <- c(0.1, 0.2, 0.1, 0.1, 0.2)
)

rownames(profile) <- c("A", "C", "G", "T")

Profile_most_Probable <- function(x) {
  myprob <- prod(
    profile["T",][which(x == "T")] %>% prod(),
    profile["A",][which(x == "A")] %>% prod(),
    profile["G",][which(x == "G")] %>% prod(),
    profile["C",][which(x == "C")] %>% prod()
  )
  
  return(myprob)
}


myprob_vector <- mylist %>% map(Profile_most_Probable) %>% unlist() 

mylist[which(myprob_vector == max(myprob_vector))]


# Given a profile matrix Profile, we can evaluate the probability of every k-mer in a string Text and find a Profile-most probable k-mer in Text, i.e., a k-mer that was most likely to have been generated by Profile among all k-mers in Text. For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT. Indeed, every other 12-mer in this string has probability 0. In general, if there are multiple Profile-most probable k-mers in Text, then we select the first such k-mer occurring in Text.
# 
# Profile-most Probable k-mer Problem: Find a Profile-most probable k-mer in a string.
# 
# Input: A string Text, an integer k, and a 4 × k matrix Profile.
# Output: A Profile-most probable k-mer in Text.
# 
# Sample Input:
#   
#   ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT
# 5
# 0.2 0.2 0.3 0.2 0.3
# 0.4 0.3 0.1 0.5 0.1
# 0.3 0.3 0.5 0.2 0.4
# 0.1 0.2 0.1 0.1 0.2
# Sample Output:
#   
#   CCGAG

library(data.table)
library(tidyverse)

mystring <- fread("dataset_159_3.txt", fill = TRUE) %>% names() 

mystr <- mystring %>% str_split(., "") %>% .[[1]]

k <- fread("dataset_159_3.txt", fill = TRUE) %>% .[1, 1] %>% pull() %>% as.numeric()

profile <- rbind(
  A <- fread("dataset_159_3.txt", fill = TRUE) %>% .[-1,1] %>% pull() %>% .[1] %>% noquote() %>% str_split(., " ")%>% .[[1]] %>% as.numeric(),
  C <- fread("dataset_159_3.txt", fill = TRUE) %>% .[-1,1] %>% pull() %>% .[2] %>% noquote() %>% str_split(., " ")%>% .[[1]] %>% as.numeric(),
  G <- fread("dataset_159_3.txt", fill = TRUE) %>% .[-1,1] %>% pull() %>% .[3] %>% noquote() %>% str_split(., " ")%>% .[[1]] %>% as.numeric(),
  T <- fread("dataset_159_3.txt", fill = TRUE) %>% .[-1,1] %>% pull() %>% .[4] %>% noquote() %>% str_split(., " ")%>% .[[1]] %>% as.numeric()
)


# generate all the k-mer 

# create a place holder list
mylist <- vector(mode = "list", length = (length(mystr) - k + 1))

# put all the K-mer into mylist
for (i in 1:(length(mystr) - k + 1)) {
  mylist[[i]] <- mystr[i:(i + k - 1)]
}



rownames(profile) <- c("A", "C", "G", "T")

Profile_most_Probable <- function(x) {
  myprob <- prod(
    profile["T",][which(x == "T")] %>% prod(),
    profile["A",][which(x == "A")] %>% prod(),
    profile["G",][which(x == "G")] %>% prod(),
    profile["C",][which(x == "C")] %>% prod()
  )
  
  return(myprob)
}


myprob_vector <- mylist %>% map(Profile_most_Probable) %>% unlist() 

mylist[which(myprob_vector == max(myprob_vector))] %>% .[[1]] %>% paste(collapse = "")



